name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: eks-local

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4
      
      - name: Setup Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
      
      - name: Update image tag
        working-directory: k8s/overlays/production
        run: |
          kustomize edit set image \
            fiap-todo-api=${{ secrets.ECR_URI }}/fiap-todo-api:${{ github.sha }}
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8s/overlays/production
          kubectl rollout status deployment/prod-fiap-todo-api
      
      - name: Smoke test
        continue-on-error: true
        run: |
          echo "Aguardando os pods ficarem prontos..."
          kubectl wait --for=condition=ready pod -l app=fiap-todo-api --timeout=120s
          echo "Smoke test passed. Pods em execucao."
      
      - name: Deployment summary
        run: |
          echo "## Kubernetes Deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Cluster: ${{ env.CLUSTER_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "Image: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Pods:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          kubectl get pods -l app=fiap-todo-api >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY